[package]
name = "ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isatty = "0.1.5"
phf = { version = "0.11.1", features = ["macros"]}
term_grid = "0.2.0"
term_size = "0.3.2"
